spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: false
    jdbc:
      time_zone: UTC
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres
  datasource:
    url: 'jdbc:postgresql://postgres:5432/tenpo_challenge'
    username: postgres
    password: password
  main:
    banner-mode: 'off'
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    org:
      springframework: INFO

jwt:
  secret: secret
  expiration: 300

tenpo:
  rest:
    client:
      get-percent:
        baseUrl: 'https://www.randomnumberapi.com/api/v1.0/random?min=0&max=100'

resilience4j:
  circuitbreaker:
    instances:
      percentageService:
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 30
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      percentageService:
        maxAttempts: 3 #3 retry
        waitDuration: 15s
  ratelimiter:
    instances:
      percentageService:
        limitForPeriod: 1
        limitRefreshPeriod: 1800s #30 minutes
        timeoutDuration: 0